### ISSUE TITLE
switch_to_window is deprecated

### ISSUE THREAD

**Issue by FannyVieira** [mozilla/fxapom#195]
https://github.com/mozilla/fxapom/blob/8dfa0550644470a36342add588acecd98b13412e/fxapom/pages/base.py#L17
check up the [documentation](http://selenium-python.readthedocs.io/api.html):
![captura de tela de 2018-02-15 21-19-50](https://user-images.githubusercontent.com/14113480/36287846-2c790018-1296-11e8-94d0-4ae2f2b9755f.png)

**Comment by FannyVieira** [comment]
do i can open a pr?

**Comment by jrbenny35** [comment]
Seems like its deprecated but still works?? Either way, I'd say a PR is fine.

**Comment by jrbenny35** [comment]
Fixed in #196
