### ISSUE TITLE
Cut a new release of fxapom to pypi

### ISSUE THREAD

**Issue by stephendonner** [mozilla/fxapom#228]
Given all the changes (transparent to the end-user as they might be) under the hood, I'd say we should probably think about cutting a new release.

Thoughts, @davehunt?  I'm willing to attempt it, it's just been such a long time and I will need help doing so, I'm sure.

Also, appropriate version #?

**Comment by davehunt** [comment]
Sure, there are no new feature so it would be a point release. Try this:

```
git tag v1.10.2
git push upstream v1.10.2
```

That's all you need, assuming the mozilla fork is named upstream in your remotes. Otherwise, call it whatever you have named it.

**Comment by stephendonner** [comment]
Thanks; I've done that, with no errors, from the commandline.  I also see that you've already tagged said release in GitHub: https://github.com/mozilla/fxapom/releases/tag/v1.10.2

I'm now reading through https://packaging.python.org/tutorials/distributing-packages/#id71 to release the package to pypi, although am stuck at exactly which step(s) I should start, and do?

**Comment by stephendonner** [comment]
Done in https://pypi.python.org/pypi/fxapom/1.10.2 and https://github.com/mozilla/fxapom/releases/tag/v1.10.2 - closing out.
