### ISSUE TITLE
Update PyFxA to latest version

### ISSUE THREAD

**Issue by davehunt** [mozilla/fxapom#24]
We're pinned to 0.0.8 but the latest version is current 0.1.1.

**Comment by davehunt** [comment]
@stephendonner did you want to take care of this one, as it applies to updating requirements?

**Comment by bobsilverberg** [comment]
@davehunt @stephendonner I am pretty sure you will run into issues trying to do this, as I did before, which is why it's pinned to 0.0.8. That's not to say you shouldn't try, but expect to encounter issues that might take some extra work to overcome.

**Comment by stephendonner** [comment]
@davehunt @bobsilverberg I'll give it a try, but someone else can feel free to steal this from me in the interim :-)

**Comment by stephendonner** [comment]
This was done successfully in https://github.com/mozilla/fxapom/pull/27
