### ISSUE TITLE
Bump version number and release to PyPi

### ISSUE THREAD

**Issue by stephendonner** [mozilla/fxapom#28]
Per https://github.com/mozilla/fxapom/pull/25#issuecomment-198259886 (and since https://github.com/mozilla/fxapom/pull/27 landed), we should:

1. bump the version number
2. release to PyPi

**Comment by rbillings** [comment]
@stephendonner what version number? Can you add steps for how to release to PyPi?

**Comment by davehunt** [comment]
This should probably be a minor version bump. Currently the version is 1.7.1 so we'd bump it to 1.7.2. Releasing to PyPI requires someone to have a PyPI account and be a maintainer or owner of the package. That's currently @bobsilverberg, @silne30, and myself. If you want to be a maintainer sign up for an account at https://pypi.python.org/ and let me know your username. Once that's done I'd be happy to guide you through the release process.

**Comment by davehunt** [comment]
I do wonder if we should update PyFxA again before releasing though, as it might resolve our current test failure due to rate limiting. I think @stephendonner might know more.

**Comment by rfk** [comment]
Yes, please update to latest PyFxA to pull in some recent fixes

**Comment by stephendonner** [comment]
Updated to PyFxA 0.1.3 in https://github.com/mozilla/fxapom/pull/30
