### ISSUE TITLE
Package and release new version to PyPi?

### ISSUE THREAD

**Issue by stephendonner** [mozilla/fxapom#46]
It's been a while, and there have been a few updates - perhaps it's time we did a PyPi release, @davehunt?

**Comment by davehunt** [comment]
Perhaps this is a good time to set FxAPOM up for automatic releases on tags, like I did with pytest-repeat. See these commits:

* https://github.com/pytest-dev/pytest-repeat/commit/b267d801cc199c6916a67804786e6df145361be3
* https://github.com/pytest-dev/pytest-repeat/commit/4e115664bc127cd302090978ceccbacafc7997aa
* https://github.com/pytest-dev/pytest-repeat/commit/3b04341c9a737b626e7f4b1add392ae4c3cf9bc2

Maybe a good topic for a hack session?

**Comment by stephendonner** [comment]
@davehunt yep, sounds good; as we discussed, learning how to do that is on my list already, so I'll take it :-)
