### ISSUE TITLE
Add support for python 3.5

### ISSUE THREAD

**Issue by davehunt** [mozilla/fxapom#47]
A few suites depend on this package, and we won't be able to update those suites to run on python 3 until this one does. Let's add support for the latest stable version (3.5) and ensure we're running tests in Travis to avoid regressions.

**Comment by frankrousseau** [comment]
Hello Davehunt, I would like to help on this. But when I run the test suite inside a virtualenv environment it complains about flake8 issues on non related packages. Are you sure that the test call doesn't require any parameter?

**Comment by davehunt** [comment]
@frankrousseau it looks like flake8 is discovering files from a virtualenvironment folder. What directory are you in when running Tox? Do you have a `.virtualenv` directory present?

**Comment by frankrousseau** [comment]
Yes I use virtualenv and have a directory dedicated to it. What is the right way to tell to tox to ignore it?

**Comment by davehunt** [comment]
@frankrousseau tox is a manager for virtual environments, so you don't need to do that yourself. If you want to install tox inside a virtual environment instead of globally, you might find it best to have your virtual environment directory outside of the current working directory. That way it won't be picked up by flake8.

**Comment by frankrousseau** [comment]
Ok, I will learn more about tox and run the tests again. Thank you.

**Comment by frankrousseau** [comment]
Ok flake8 tests are now green. But marionette tests failed. Can you give a pointer to a documentation explaining how to isolate them (like suggesting in the PR thread)?

**Comment by frankrousseau** [comment]
I managed to do it by using environment variable. I let you chech the PR.

**Comment by davehunt** [comment]
Fixed in #52 - thanks @frankrousseau! 🎉
