### ISSUE TITLE
Add PYTEST_DEBUG for Travis-CI run debugging/support help?

### ISSUE THREAD

**Issue by stephendonner** [mozilla/fxapom#86]
Per our Travis-CI support conversation, we might want to look at adding PYTEST_DEBUG and doing a run w/output, and submitting to them.

/cc @davehunt

**Comment by davehunt** [comment]
This can probably just be added to the global environment variables here: https://github.com/mozilla/fxapom/blob/master/.travis.yml#L10 and may also need to be added to Tox's passenv here: https://github.com/mozilla/fxapom/blob/master/tox.ini#L5

We should do this in a pull request and rerun the job until we encounter a failure, so we don't need to land these changes in our master branch.

**Comment by stephendonner** [comment]
PR up and running in Travis: https://github.com/mozilla/fxapom/pull/88

**Comment by davehunt** [comment]
Closing for now. We can reopen if we see this again now that we've removed support for Marionette.
