### ISSUE TITLE
Review requirements.txt and setup.py

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/fxapom#9]
I had some trouble today with the latest version of FxAPom when I removed `PyFxA==0.0.6` from `requirements.txt` assuming we could just rely on the fact that that package is also specified in `setup.py`. Jenkins wasn't happy about this though, so I reverted the change. I am guessing that I am just not doing something right, so would appreciate another set of eyes on this.

@davehunt Please ping me when you have some time to discuss this.

**Comment by davehunt** [comment]
It looks like PyFxA is successfully installed, but running `python setup.py install` on Jenkins is causing an issue when installing mock: `mock requires setuptools>=17.1. Aborting installation`

**Comment by davehunt** [comment]
I've updated pip and virtualenv on our Jenkins instances and this appears to have resolved the issue.

**Comment by bobsilverberg** [comment]
@davehunt I'm not sure this should be closed as I backed out my change, which should perhaps be re-applied. Should I remove PyFxA from requirements.txt and keep it just in setup.py, in your opinion?

**Comment by davehunt** [comment]
Oh, I didn't realise there was a code backout. I see now you mentioned reverting a change, but I thought this was regarding the Jenkins configuration. I think we should use either setup.py or requirements.txt. The exception here is that running the tests for fxapom has an additional requirement of our pytest plugin (and be extension, pytest). I think there's a way to define test requirements in setup.py but I've not tried it before. If requirements.txt is just for running tests, we could move it into the tests directory.
