### ISSUE TITLE
Update to be Python3 compatible

### ISSUE THREAD

**Issue by eviljeff** [mozilla/fxapom#97]
AMO is looking (https://github.com/mozilla/addons-server/issues/4997) to move to Python3 by the end of 2017 and this is a dependency so can fxapom be upgraded also?
Looks like Travis is already testing with py3 so it's bound to be straightforward, right? 😆

**Comment by davehunt** [comment]
This was done in https://github.com/mozilla/fxapom/issues/47. Do you have details regarding issues with Python 3? Unfortunately running the *tests* for FxAPOM now depends on mozlog, which does not support Python 3, but I'm sure we could overcome that for Travis, as we don't need to use mozlog there.

**Comment by davehunt** [comment]
I opened https://github.com/mozilla/fxapom/pull/98 to see if I can get Travis passing, but it's failed. Might be that we can't even have mozlog installed. I can't see the build log at the moment, but will check back later.

**Comment by davehunt** [comment]
Okay, that's passing now.. once it's merged I'd say we can close this.

**Comment by eviljeff** [comment]
We don't have any details on any python3 problems yet tbh - we've not even started trying to get it to run because we had 22 dependencies and getting most of them upgraded seemed like a blocker.  Seems like we can take package off the list too.
